### ISSUE TITLE
outdated documentation and problem downloading database

### ISSUE THREAD

**Issue by latimerb** [AllenInstitute/aisynphys#128]
I'm following the documentation on this page: https://github.com/AllenInstitute/aisynphys/blob/current-release/doc/source/interactive_tools.rst

When I issue the command
`python tools/synaptic_dynamics.py --db-version=full`
I get
`KeyError: "Unknown database version; options are: ['synphys_r1.0_2019-08-29_small.sqlite', 'synphys_r1.0_2019-08-29_medium.sqlite', 'synphys_r1.0_2019-08-29_full.sqlite', 'synphys_r1.0_small.sqlite', 'synphys_r1.0_medium.sqlite', 'synphys_r1.0_full.sqlite', 'synphys_r2.0-pre1_small.sqlite', 'synphys_r2.0-pre1_medium.sqlite', 'synphys_r2.0-pre1_full.sqlite', 'synphys_r2.0-pre2_small.sqlite', 'synphys_r2.0-pre2_medium.sqlite', 'synphys_r2.0-pre3_small.sqlite', 'synphys_r2.0-pre3_medium.sqlite', 'synphys_r2.0-pre4_small.sqlite', 'synphys_r2.0-pre4_medium.sqlite']"`

Which is fine, I can just switch "full" to "synphys_r2.0-pre1_full.sqlite" for example, but this should be updated in the docs.

However, when I attempt this:
`python tools/synaptic_dynamics.py --db-version=synphys_r2.0-pre1_full.sqlite`
I get:
`Traceback (most recent call last):
  File "/Volumes/TOSHIBA EXT/aisynphys/tools/synaptic_dynamics.py", line 5, in <module>
    from aisynphys.database import default_db as db
  File "/Volumes/TOSHIBA EXT/aisynphys/aisynphys/__init__.py", line 2, in <module>
    from . import config
  File "/Volumes/TOSHIBA EXT/aisynphys/aisynphys/config.py", line 68, in <module>
    sqlite_file = get_db_path(args.db_version)
  File "/Volumes/TOSHIBA EXT/aisynphys/aisynphys/synphys_cache.py", line 37, in get_db_path
    interactive_download(url, cache_file)
  File "/Volumes/TOSHIBA EXT/aisynphys/aisynphys/util.py", line 404, in interactive_download
    size = get_url_download_size(url)
  File "/Volumes/TOSHIBA EXT/aisynphys/aisynphys/util.py", line 386, in get_url_download_size
    file_size = int(urlopen(url).info().get('Content-Length', None))
  File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

I should note that I installed the repo in my external hard drive so that may be causing this issue? If so, how do I install the package on my machine and download the full database to another location (such as my external hard drive)?

**Comment by campagnola** [comment]
Hello Ben, sorry for the delay; I've been on vacation.
When I run the same command on my system, I get:

$ python tools/synaptic_dynamics.py --db-version=full
No supported database found for requested size 'full' (use --list-db_versions to see currently supported files)

I think the difference is because you have an older version of our code. In this case, the error shows up because we haven't publicly released the full version of our latest database (we are currently on a pre-release; the full version will come with our 2.0 release). I'll note this in the documentation.

Meanwhile, I suggest checking out the notebooks under doc/ or the matrix analyzer tool, as these should work fine with the small database version.
Or if there's something you're interested in doing with the full database, I can get you access to our postgres server before the public data release.


Cheers,
Luke

________________________________
From: Ben Latimer ***@***.***>
Sent: Friday, August 13, 2021 05:28
To: AllenInstitute/aisynphys ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AllenInstitute/aisynphys] outdated documentation and problem downloading database (#128)


I'm following the documentation on this page: https://github.com/AllenInstitute/aisynphys/blob/current-release/doc/source/interactive_tools.rst<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAllenInstitute%2Faisynphys%2Fblob%2Fcurrent-release%2Fdoc%2Fsource%2Finteractive_tools.rst&data=04%7C01%7C%7Cc0e549b2e78c478846b908d95e55dc19%7C32669cd6737f4b398bddd6951120d3fc%7C0%7C0%7C637644545149574882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=smv4a%2FnsMwoN5OjeM8MrSNBARL3fbaZZYicJeYxNb2A%3D&reserved=0>

When I issue the command
python tools/synaptic_dynamics.py --db-version=full
I get
KeyError: "Unknown database version; options are: ['synphys_r1.0_2019-08-29_small.sqlite', 'synphys_r1.0_2019-08-29_medium.sqlite', 'synphys_r1.0_2019-08-29_full.sqlite', 'synphys_r1.0_small.sqlite', 'synphys_r1.0_medium.sqlite', 'synphys_r1.0_full.sqlite', 'synphys_r2.0-pre1_small.sqlite', 'synphys_r2.0-pre1_medium.sqlite', 'synphys_r2.0-pre1_full.sqlite', 'synphys_r2.0-pre2_small.sqlite', 'synphys_r2.0-pre2_medium.sqlite', 'synphys_r2.0-pre3_small.sqlite', 'synphys_r2.0-pre3_medium.sqlite', 'synphys_r2.0-pre4_small.sqlite', 'synphys_r2.0-pre4_medium.sqlite']"

Which is fine, I can just switch "full" to "synphys_r2.0-pre1_full.sqlite" for example, but this should be updated in the docs.

However, when I attempt this:
python tools/synaptic_dynamics.py --db-version=synphys_r2.0-pre1_full.sqlite
I get:
Traceback (most recent call last): File "/Volumes/TOSHIBA EXT/aisynphys/tools/synaptic_dynamics.py", line 5, in <module> from aisynphys.database import default_db as db File "/Volumes/TOSHIBA EXT/aisynphys/aisynphys/__init__.py", line 2, in <module> from . import config File "/Volumes/TOSHIBA EXT/aisynphys/aisynphys/config.py", line 68, in <module> sqlite_file = get_db_path(args.db_version) File "/Volumes/TOSHIBA EXT/aisynphys/aisynphys/synphys_cache.py", line 37, in get_db_path interactive_download(url, cache_file) File "/Volumes/TOSHIBA EXT/aisynphys/aisynphys/util.py", line 404, in interactive_download size = get_url_download_size(url) File "/Volumes/TOSHIBA EXT/aisynphys/aisynphys/util.py", line 386, in get_url_download_size file_size = int(urlopen(url).info().get('Content-Length', None)) File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 214, in urlopen return opener.open(url, data, timeout) File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 523, in open response = meth(req, response) File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 632, in http_response response = self.parent.error( File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 561, in error return self._call_chain(*args) File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 494, in _call_chain result = func(*args) File "/opt/anaconda3/envs/aisynphys/lib/python3.9/urllib/request.py", line 641, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 403: Forbidden

I should note that I installed the repo in my external hard drive so that may be causing this issue? If so, how do I install the package on my machine and download the full database to another location (such as my external hard drive)?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAllenInstitute%2Faisynphys%2Fissues%2F128&data=04%7C01%7C%7Cc0e549b2e78c478846b908d95e55dc19%7C32669cd6737f4b398bddd6951120d3fc%7C0%7C0%7C637644545149584876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=upI83saQCZv59XxNd5UB1kMNwe5bQ0UzC7MiehvP2Rg%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHFUJCCLJRBGYM4XVBAEE3T4UFW5ANCNFSM5CDPZKIA&data=04%7C01%7C%7Cc0e549b2e78c478846b908d95e55dc19%7C32669cd6737f4b398bddd6951120d3fc%7C0%7C0%7C637644545149594868%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=epsf0picB%2BCSuJQOSXPDoT2eINroo8op13kG6sstvMc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc0e549b2e78c478846b908d95e55dc19%7C32669cd6737f4b398bddd6951120d3fc%7C0%7C0%7C637644545149594868%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zlN5Vt0TEkKNjiYbyZLbjG4p6AkfNvXoSpde8afUp8E%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7Cc0e549b2e78c478846b908d95e55dc19%7C32669cd6737f4b398bddd6951120d3fc%7C0%7C0%7C637644545149604864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qfPaemFpJ%2FZ75el1XKzk2ytajWJl8q7BR6uocwyv%2F7w%3D&reserved=0>.
